### ISSUE TITLE
Please use this binary this will fix the problem.

### ISSUE THREAD

**Issue by siborg** [Sinuslabs/Reach#14]
Please use this binary this will fix the problem.
https://github.com/Sinuslabs/Reach/releases/latest/download/reach-installer.tar.gz

_Originally posted by @oskarsh in https://github.com/Sinuslabs/Reach/issues/10#issuecomment-1401855752_
            
The issue persists. Bitwig still does not load the plugin successfully. Same error about async reply as before.

**Comment by oskarsh** [comment]
Please move the discussion to this thread -> [Issue 10](https://github.com/Sinuslabs/Reach/issues/10)
