### ISSUE TITLE
I Can't Register Reach

### ISSUE THREAD

**Issue by maxxatgit** [Sinuslabs/Reach#9]
Greetings!

I purchased a license to use Reach. The demo sounds great, but I can't activate it.

I tried pasting the serial # in the display, I tried typing in my login credentials, nothing works.

I'm on Ubuntu 22.04.1 LTS, Reaper native Linux

**Comment by oskarsh** [comment]
I am currently experiencing some issues with the libcurl library not allowing any network calls made from the plugin. Please write me a email to hello@sinuslabs.io I will provide a working version compiled for you.

**Comment by oskarsh** [comment]
@maxxatgit I've updated the installer inside the release you will now be able to install and activate reach for the Linux Version! Thanks for hanging in there <3

**Comment by maxxatgit** [comment]
Hi.

I seem to remember using Reach after the fix, and it worked. It registered.
Now, it is saying it's not registered....

Does it check back every time it's launched?

I try to register with my email and password - which works at the Sinuslabs
site, but the plugin says bad credentials.

Please help.

Regards,
Paul

**Comment by maxxatgit** [comment]
Sorry for the repeat emails...

I just tried the serial #... still not activated.

**Comment by maxxatgit** [comment]
I closed Reaper, re-opened it, and pasted the serial #, it worked. I closed
Reaper again, re-opened it, and Reach is still activated. Strange, but I'm
glad it's working OK now.
Thanks!

**Comment by oskarsh** [comment]
I am storing the activation data on your System. Its in the ~/.config/Sinuslabs folder. You should be able to find the Reach folder there with the activation data. 

As long as you are not copying reach from one computer to the other with the same activation you will be fine.
